const Colors = {
  orange: '#E65100',
  black: '#000000',
  white: '#ffffff',
  cyan: '#00838F',
  lightGreen: '#23C552',
  lightblue: '#ADD8E6',
  darkblue: '#00008B',
  pink: '#FFC0CB',
  kournikova: '#ffe767',
  darkModerateViolet: '#513788',
  red: '#FF0000',
  heather: '#AAB8C2',
  amaranth: '#E2264D',
  wisteria: '#CC8EF5',
  riptide: '#8DE8C3',
  madang: '#B0D5A5',
  greenMist: '#C7C59E',
  pancho: '#DEBD90',
  yuma: '#C3B889',
  vistaBlue: '#9ADEBA',
  mauvelous: '#F48EA7',
  lily: '#D08CB3',
  blueBell: '#9B95C5',
  pictonBlue: '#679AD7',
  summerSky: '#349EEE',
  lightSkyBlue: '#91D2FA',
  charlotte: '#96D8E9',
  iceCold: '#9FE1CE',
  fringyFlower: '#A6ECB6',
  greenMadang: '#B0F69A',
  bilobaFlower: '#B091F5',
  portage: '#8894F2',
  cornFlowerBlue: '#5F98F1',
  lightSummerSky: '#33ADE1',
  darkRipTide: '#9AD7C2',
  jungleMist: '#B1C2C5',
  lilac: '#C8ABC4',
  shocking: '#E094C4',
  orchid: '#D979CA',
  paleCornFlowerBlue: '#9EC6F9',
  perano: '#AEB5F8',
  perfume: '#C4A6F9',
  mauve: '#D59CF3',
  plum: '#D294D3',
  petiteOrchid: '#DF9E9E',
  sandyBrown: '#E6A766',
  brightSun: '#F2B92F',
  darkYellow: '#fca819',
  darkRed: '#ff2b3e',
  navyBlue: '#01579B',
  lightPurple60: '#E6E6FA99',
  pastelRed: '#ff6961',
  alto: '#dddddd',
  dodgerBlue: '#a9e7ff',
  lightSky: '#ccedff',
  tangerineYellow: '#FFCE00',
  silver: '#BCBCBC',
  green: '#5fc662',
  purple: '#4f13c6',
  shadowGreen: '#5fc662e6',
  brightOrange: '#FFAC1C',
  blue700: '#0288D1',
  mayaBlue: '#69c7ff',
  pink400: '#EC407A',
  mediumAquamarine: '#76CCB0',
};

export const getRandomColorsArray = () => [
  [
    Colors.riptide,
    Colors.riptide,
    Colors.madang,
    Colors.greenMist,
    Colors.pancho,
    Colors.yuma,
  ],
  [
    Colors.riptide,
    Colors.riptide,
    Colors.vistaBlue,
    Colors.madang,
    Colors.greenMist,
    Colors.pancho,
  ],
  [
    Colors.mauvelous,
    Colors.lily,
    Colors.blueBell,
    Colors.pictonBlue,
    Colors.summerSky,
    Colors.summerSky,
  ],
  [
    Colors.mauvelous,
    Colors.mauvelous,
    Colors.lily,
    Colors.blueBell,
    Colors.pictonBlue,
    Colors.summerSky,
  ],
  [
    Colors.lightSkyBlue,
    Colors.charlotte,
    Colors.iceCold,
    Colors.fringyFlower,
    Colors.greenMadang,
    Colors.madang,
  ],
  [
    Colors.lightSkyBlue,
    Colors.lightSkyBlue,
    Colors.charlotte,
    Colors.iceCold,
    Colors.fringyFlower,
    Colors.greenMadang,
  ],
  [
    Colors.wisteria,
    Colors.bilobaFlower,
    Colors.portage,
    Colors.cornFlowerBlue,
    Colors.summerSky,
    Colors.lightSummerSky,
  ],
  [
    Colors.lightSkyBlue,
    Colors.lightSkyBlue,
    Colors.charlotte,
    Colors.iceCold,
    Colors.fringyFlower,
    Colors.greenMadang,
  ],
  [
    Colors.riptide,
    Colors.darkRipTide,
    Colors.jungleMist,
    Colors.lilac,
    Colors.shocking,
    Colors.orchid,
  ],
  [
    Colors.riptide,
    Colors.riptide,
    Colors.darkRipTide,
    Colors.jungleMist,
    Colors.lilac,
    Colors.shocking,
  ],
  [
    Colors.lightSkyBlue,
    Colors.paleCornFlowerBlue,
    Colors.perano,
    Colors.perfume,
    Colors.mauve,
    Colors.mauve,
  ],
  [
    Colors.lightSkyBlue,
    Colors.lightSkyBlue,
    Colors.paleCornFlowerBlue,
    Colors.perano,
    Colors.perfume,
    Colors.mauve,
  ],
  [
    Colors.wisteria,
    Colors.plum,
    Colors.petiteOrchid,
    Colors.sandyBrown,
    Colors.brightSun,
    Colors.brightSun,
  ],
  [
    Colors.wisteria,
    Colors.wisteria,
    Colors.plum,
    Colors.petiteOrchid,
    Colors.sandyBrown,
    Colors.brightSun,
  ],
];

export default Colors;
