export default {
  HOME: 'Home Screen',
  INDICATOR: 'Indicator Component',
  STRIKE_IMAGE: 'Strike Image',
  NOTIFICATION: 'Notification',
  THEME_SWITCH: 'Skia Theme Switch',
  SKIA_LIKE: 'Skia Like',
  WALLET: 'Wallet Component',
  ANIMATED_SCANNER: 'Animated Scanner',
  MEDIA_BUTTON: 'Media Button',
  HEART_RATE: 'Heart Rate',
  WIRELESS_CHARGER: 'Wireless Charger',
  SKIA_CHARGING: 'Skia Charging',
  ANIMATEDCHECKMARK: 'Animated Checkmark',
  SKIA_SIGNAL_WIFI: 'Skia Signal Wifi',
};
