export default {
  ANIMATION_COMPONENT: 'Skia Components',
  INDICATOR: 'Indicator',
  STRIKE_IMAGE: 'Strike Image',
  NOTIFICATION: 'Notification',
  THEME_SWITCH: 'Theme Switch',
  SKIA_LIKE: 'Skia Like',
  WALLET: 'Wallet',
  ANIMATED_SCANNER: 'Animated Scanner',
  MEDIA_BUTTON: 'Media Button',
  DEFAULT_MEDIA_BUTTON_WITH_PULSE: 'Simple Media Button with Pulse (Default)',
  CUSTOM_MEDIA_BUTTON_WITH_PULSE: 'Custom Media Button with Pulse',
  SIMPLE_MEDIA_BUTTON_WITH_PULSE: 'Simple Media Button without Pulse',
  HEART_RATE: 'Heart Rate',
  WIRELESS_CHARGER: 'Wireless Charger',
  DEFAULT_HEARTRATE: 'Default HeartRate',
  FOLLOWUP_HEARTRATE: 'FollowUp HeartRate',
  SKIA_CHARGING: 'Skia Charging',
  DEFAULT_ANIMATED_CHECK_MARK:
    'Animated Checkmark with fade effect and particles(default)',
  CIRCULAR_ANIMATED_CHECK_MARK:
    'Animated Checkmark with simple circular effect',
  SIMPLE_ANIMATED_CHECKMARK: 'Animated Checkmark with simple effect',
  ANIMATED_CHECKMARK: 'Animated Checkmark',
};
