export default {
  ANIMATION_COMPONENT: 'Skia Components',
  INDICATOR: 'Indicator',
  STRIKE_IMAGE: 'Strike Image',
  NOTIFICATION: 'Notification',
  THEME_SWITCH: 'Theme Switch',
  SKIA_LIKE: 'Skia Like',
  WALLET: 'Wallet',
  ANIMATED_SCANNER: 'Animated Scanner',
  MEDIA_BUTTON: 'Media Button',
  DEFAULT_MEDIA_BUTTON_WITH_PULSE: 'Simple Media Button with Pulse (Default)',
  CUSTOM_MEDIA_BUTTON_WITH_PULSE: 'Custom Media Button with Pulse',
  SIMPLE_MEDIA_BUTTON_WITH_PULSE: 'Simple Media Button without Pulse',
  HEART_RATE: 'Heart Rate',
};
